---
  - name: Get OAuth Token
    uri:
      url: "https://login.microsoftonline.com/{{ azure_tenant_id }}/oauth2/v2.0/token"
      method: POST
      body_format: form-urlencoded
      body:
        grant_type: password
        client_id: "{{ azure_client_id }}"
        client_secret: "{{ azure_client_secret }}"
        username: "{{ azure_username }}"
        password: "{{ azure_password }}"
        scope: "499b84ac-1321-427f-aa17-267ca6975798/.default"
      status_code: 200
      return_content: yes
    register: token_response

  - name: Create Token
    uri:
      url: "https://vssps.dev.azure.com/{{ azure_organization_name }}/_apis/tokens/pats?api-version=7.0-preview.1"
      method: POST
      headers:
        Authorization: "Bearer {{ token_response.json.access_token }}"
      body_format: json
      body:
        displayName: "{{ azure_token_name }}"
        scope: "{{ scope }}"
      status_code: 200
      return_content: yes
    register: create_token_response

  - name: Display Create Token Response
    debug:
      var: create_token_response.json
